<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>9603e6bf-d2f9-4136-9ad4-5f6da6446ce5</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.16" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
		<PackageReference Include="Serilog" Version="4.2.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.2" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="8.0.2" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Controllers\" />
		<Folder Include="Client\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OxCore.QuantumQueue.Application\OxCore.QuantumQueue.Application.csproj" />
		<ProjectReference Include="..\OxCore.QuantumQueue.SharedKernel\OxCore.QuantumQueue.SharedKernel.csproj" />
	</ItemGroup>

</Project>
