<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Company>OxCore</Company>
		<Title>OxCore Quantum Queue</Title>
		<Authors>Prabuddha Jayawardhana</Authors>
		<Product>OxCore.QuantumQueue.Core</Product>
		<PackageId>OxCore.QuantumQueue.Core</PackageId>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>QuantumQueue.jpg</PackageIcon>
		<NeutralLanguage>en-001</NeutralLanguage>
		<Version>9.0.2</Version>
		<AssemblyVersion>9.0.2</AssemblyVersion>
		<FileVersion>9.0.2</FileVersion>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<ProduceReferenceAssembly>true</ProduceReferenceAssembly>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Copyright>OxCore Team</Copyright>
		<PackageTags>Scheduler, Task, JobRunner, Job</PackageTags>
		<Description>OxCore.QuantumQueue is a lightweight, CRON-based job scheduler for .NET applications. Designed to be modular and developer-friendly, it lets you easily run background tasks with precise control over execution timing.</Description>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageProjectUrl>https://github.com/prabuddhajayawardhana/QuantumQueue</PackageProjectUrl>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.4" />
		<PackageReference Include="OxCore.QuantumQueue.SharedKernel" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<None Include="..\..\..\Icon\QuantumQueue.jpg" Link="Icon\QuantumQueue.jpg">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Icon\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\OxCore.QuantumQueue.SharedKernel\OxCore.QuantumQueue.SharedKernel.csproj" />
	</ItemGroup>

</Project>
