<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Company>OxCore</Company>
		<Title>OxCore Quantum Queue</Title>
		<Authors>Prabuddha Jayawardhana</Authors>
		<Product>OxCore.QuantumQueue.Core</Product>
		<PackageId>OxCore.QuantumQueue.Core</PackageId>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>QuantumQueue.jpg</PackageIcon>
		<Version>8.0.11</Version>
		<NeutralLanguage>en-001</NeutralLanguage>
		<AssemblyVersion>8.0.11</AssemblyVersion>
		<FileVersion>8.0.11</FileVersion>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<ProduceReferenceAssembly>true</ProduceReferenceAssembly>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<BuildOutputTargetFolder>ref</BuildOutputTargetFolder>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<None Include="..\..\..\Icon\QuantumQueue.jpg" Link="Icon\QuantumQueue.jpg">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Icon\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="OxCore.QuantumQueue.SharedKernel" Version="8.0.0" />
	</ItemGroup>

</Project>
